### ISSUE TITLE
Token is not entered into mongo database

### ISSUE THREAD

**Issue by omnicortex** [songyuew/teller#3]
I went through the entire process and got the token displayed in the console, but no token is recorded into the mongo database. I don't see any token database created either. The console shows the following error:
```
{"status":"fail","message":{"errorResponse":{"ok":0,"errmsg":"Command insert requires authentication","code":13,"codeName":"Unauthorized"},"ok":0,"code":13,"codeName":"Unauthorized"}}
```
Seems like the app is not authenticated. My config
```
MONGODB_CONNECTION_STRING> mongodb://localhost:27017
DB_PASSWORD> example
```
My MongoDB settings are all defaults. The app never ask for the MongoDB username.

**Comment by omnicortex** [comment]
Adding the username and password to the MongoDB connection string solves the problem. Thank you for this project.

**Comment by songyuew** [comment]
> Adding the username and password to the MongoDB connection string solves the problem. Thank you for this project.

No worries!
